const countryCode = {
  ALL: "All",
  ARG: "Argentina",
  BRA: "Brazil",
  CAN: "Canada",
  CHN: "China",
  DEU: "Germany",
  ESP: "Span",
  FRA: "France",
  GBR: "United Kingdom",
  IDN: "Indonesia",
  IND: "India",
  ITA: "Italy",
  JPN: "Japan",
  MEX: "Mexico",
  NGA: "Nigeria",
  KOR: "Korea",
  RUS: "Russia",
  SAU: "Saudi Arabia",
  TUR: "Turkey",
  USA: "United States of America",
  ZAF: "South Africa",
  AFE: "NA",
  AFN: "NA",
  AFS: "NA",
  AFW: "NA",
  BLK: "NA",
  CAC: "Central America and Caribbean",
  EAS: "East Asia and Pacific",
  EUM: "NA",
  EUN: "European Union",
  LAE: "NA",
  LAW: "NA",
  MEA: "Middle East",
  OAS: "Organization of American States",
  OCA: "NA",
  ROW: "Rest of World"
};

module.exports = {countryCode};
